export const config = {
  name: "Transaction Monitor",
  tag: "OBSERVABILITY LAB",
  description: "Del evento individual al comportamiento del sistema.",
  post: "/api/transactions",
  list: "/api/transactions",
  sample: {
    id: "00000000-0000-4000-8000-000000000001",
    service: "PAYMENTS",
    status: "SUCCESS",
    durationMs: 250,
    occurredAt: "2026-01-01T00:00:00Z",
  },
  columns: ["id", "service", "status", "durationMs"],
  concepts: ["PostgreSQL", "Micrometer", "Percentiles"],
  scenarios: [],
  repo: "transaction-monitor",
  index: 6,
  secure: false,
  payment: false,
  monitor: true,
  brand: "pulso",
  label: "TUS OPERACIONES, EN CONTEXTO",
  title: "Mira lo que pasa.",
  emphasis: "Entiende lo que cambia.",
  intro:
    "Reúne operaciones, tiempos y resultados en un mismo lugar. Explora el detalle y encuentra señales de degradación por servicio.",
  accent: "#5bbdab",
  soft: "#eff5f3",
  kind: "monitor",
  form: "Registra una operación",
  button: "Registrar evento",
  steps: [
    "Registra el resultado",
    "Explora la actividad",
    "Observa las métricas",
  ],
  features: [
    [
      "01",
      "Cada operación cuenta",
      "Registra eventos únicos y consulta su detalle.",
    ],
    [
      "02",
      "La velocidad importa",
      "Mide tiempos de procesamiento y distribución de latencias.",
    ],
    [
      "03",
      "El contexto también",
      "Separa resultados por servicio para entender qué cambia.",
    ],
  ],
};
